enum ProviderEnum {
  DATA_SOURCE = 'DATA_SOURCE',
  LOGGER = 'LOGGER',
  CATEGORY_REPOSITORY = 'CATEGORY_REPOSITORY',
  CATEGORY_LOGGER = 'CATEGORY_LOGGER',
  COURSE_REPOSITORY = 'COURSE_REPOSITORY',
  COURSE_LOGGER = 'COURSE_LOGGER',
}

export default ProviderEnum;
